// AI모아 — 툴 데이터 (index.html + tool.html 공유)
const TOOLS = [
  // ── 챗봇 ──────────────────────────────────────────────────────────────────
  {
    id: "chatgpt",
    name: "ChatGPT", emoji: "🤖", cat: "챗봇", free: "부분무료", hot: true,
    desc: "OpenAI 범용 AI. 글쓰기·요약·번역·분석 전방위 활용 가능",
    url: "https://chat.openai.com",
    tagline: "세상에서 가장 많이 쓰이는 AI 챗봇",
    plans: [
      { name:"Free",  price:"무료",   features:["GPT-4o mini 무제한", "GPT-4o 하루 일부 사용", "기본 이미지 생성"] },
      { name:"Plus",  price:"$20/월", features:["GPT-4o 무제한", "DALL-E 3 이미지 생성", "고급 데이터 분석", "웹 검색"] },
      { name:"Team",  price:"$25/월", features:["Plus 전부 + 팀 워크스페이스", "더 긴 컨텍스트 윈도우"] },
    ],
    pros: ["가장 쉬운 사용법, 진입장벽 없음", "GPT-4o는 이미지·음성·텍스트 모두 처리", "방대한 플러그인·GPT 생태계", "모바일 앱 완성도 높음"],
    cons: ["무료 플랜은 응답 속도·품질 제한", "최신 정보 반영이 다소 느림", "긴 문서 처리 시 Claude보다 약함"],
    useCases: ["이메일·보고서·블로그 초안 작성", "코드 오류 디버깅 및 설명", "외국어 번역 및 교정", "아이디어 브레인스토밍", "데이터 분석 및 수식 계산"],
    recommend: ["처음 AI를 써보는 분", "다양한 용도로 범용적으로 쓰고 싶은 분", "이미지 생성도 함께 쓰고 싶은 분"],
    tips: ["한국어로 질문해도 완벽하게 답변해요", "'~처럼 행동해줘' 역할 부여 시 품질이 크게 올라가요", "Custom GPT로 나만의 AI 도구를 만들 수 있어요"],
    similar: ["claude", "gemini", "perplexity"],
  },
  {
    id: "claude",
    name: "Claude", emoji: "🧠", cat: "챗봇", free: "부분무료", hot: true,
    desc: "Anthropic AI. 긴 문서 분석·코딩·창작에 특히 강함",
    url: "https://claude.ai",
    tagline: "긴 문서 분석과 코딩에 가장 강한 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["Claude Sonnet 하루 제한 사용", "기본 파일 업로드"] },
      { name:"Pro",   price:"$20/월", features:["Claude Sonnet 무제한", "Claude Opus 사용 가능", "더 긴 컨텍스트(200K 토큰)", "Projects 기능"] },
    ],
    pros: ["200K 토큰 컨텍스트로 긴 PDF·코드 한번에 분석", "답변이 논리적이고 신중함", "창작·글쓰기 품질 최상위", "한국어 실력 우수"],
    cons: ["이미지 생성 기능 없음", "무료 플랜 사용량 제한이 타 서비스보다 빠듯함", "웹 검색 기능 제한적"],
    useCases: ["긴 계약서·논문·보고서 분석", "코드 리뷰 및 전체 프로젝트 코딩", "소설·에세이 등 창작 작업", "복잡한 법률·의료 문서 요약"],
    recommend: ["긴 문서를 자주 다루는 분", "코딩 생산성을 높이고 싶은 분", "창작 작업을 하는 분", "AI 답변의 정확성·신뢰성이 중요한 분"],
    tips: ["PDF를 통째로 올려도 전부 읽어줘요", "코딩 시 전체 파일 구조까지 설명해달라고 하면 더 좋아요", "Claude Code(터미널 버전)와 함께 쓰면 개발 생산성이 극대화돼요"],
    similar: ["chatgpt", "gemini", "perplexity"],
  },
  {
    id: "gemini",
    name: "Gemini", emoji: "✨", cat: "챗봇", free: "부분무료", hot: false,
    desc: "Google AI. 실시간 검색 연동 + 멀티모달 지원",
    url: "https://gemini.google.com",
    tagline: "Google 검색과 연동되는 실시간 AI",
    plans: [
      { name:"Free",     price:"무료",   features:["Gemini 1.5 Flash", "Google 검색 연동", "이미지 업로드·분석"] },
      { name:"Advanced", price:"$19.99/월", features:["Gemini 1.5 Pro", "구글 드라이브·문서 연동", "더 긴 컨텍스트"] },
    ],
    pros: ["실시간 Google 검색으로 최신 정보 제공", "Google Workspace(Docs·Sheets) 완벽 연동", "YouTube 영상 분석 가능", "무료 플랜 넉넉함"],
    cons: ["창작·코딩은 Claude·ChatGPT보다 약함", "한국어 뉘앙스 처리가 타 모델 대비 아쉬움"],
    useCases: ["최신 뉴스·정보 검색 및 요약", "Google Docs 문서 작성 보조", "YouTube 영상 내용 정리", "구글 서비스 연동 자동화"],
    recommend: ["Google Workspace를 주로 쓰는 분", "최신 정보를 자주 검색하는 분", "무료로 시작하고 싶은 분"],
    tips: ["Google 드라이브 파일을 직접 연결해서 분석할 수 있어요", "NotebookLM(Gemini 기반)으로 문서 기반 AI 챗봇을 만들 수 있어요"],
    similar: ["chatgpt", "claude", "perplexity"],
  },
  {
    id: "perplexity",
    name: "Perplexity", emoji: "🔍", cat: "챗봇", free: "부분무료", hot: true,
    desc: "AI 검색 엔진. 출처를 인용하며 정확한 최신 정보 제공",
    url: "https://perplexity.ai",
    tagline: "출처를 보여주는 AI 검색 엔진",
    plans: [
      { name:"Free",  price:"무료",   features:["기본 AI 검색", "제한된 고급 검색"] },
      { name:"Pro",   price:"$20/월", features:["무제한 고급 검색", "GPT-4o·Claude 선택 사용", "파일 업로드 분석"] },
    ],
    pros: ["모든 답변에 출처(URL) 표시로 신뢰성 높음", "실시간 웹 검색 기반 최신 정보", "구글 검색 대체로 쓰기 좋음", "학술 논문 검색 특화 모드 보유"],
    cons: ["창작·코딩에는 적합하지 않음", "깊은 분석보다 빠른 정보 수집에 특화"],
    useCases: ["최신 트렌드·뉴스 리서치", "학술 자료 검색 및 정리", "제품 비교 및 리뷰 수집", "팩트체크"],
    recommend: ["블로거·기자·리서처", "논문을 자주 찾는 학생·연구자", "구글 검색을 AI로 대체하고 싶은 분"],
    tips: ["'Copilot 모드'로 심층 검색을 하면 훨씬 자세한 답변을 얻어요", "학술 논문은 'Academic' 검색 모드를 쓰세요"],
    similar: ["chatgpt", "gemini", "claude"],
  },

  // ── 이미지 ────────────────────────────────────────────────────────────────
  {
    id: "midjourney",
    name: "Midjourney", emoji: "🎨", cat: "이미지", free: "유료", hot: true,
    desc: "텍스트→이미지 생성 최강. 아트·디자인 작업에 필수",
    url: "https://midjourney.com",
    tagline: "전 세계 디자이너가 선택한 이미지 생성 AI",
    plans: [
      { name:"Basic",    price:"$10/월", features:["200장/월 생성", "상업적 이용 가능"] },
      { name:"Standard", price:"$30/월", features:["무제한 Relax 생성", "15시간 Fast 생성"] },
      { name:"Pro",      price:"$60/월", features:["무제한 Relax + 30시간 Fast", "스텔스 모드(비공개)"] },
    ],
    pros: ["업계 최고 수준의 이미지 품질", "독특하고 예술적인 스타일 표현", "다양한 스타일 레퍼런스 학습 가능", "활발한 커뮤니티"],
    cons: ["무료 플랜 없음 (가입 시 일부 무료 제공)", "Discord 기반이라 처음엔 불편함", "텍스트 렌더링은 약함"],
    useCases: ["SNS·블로그 썸네일 제작", "브랜드 비주얼 콘셉트 작업", "일러스트·아트워크 생성", "광고 소재 시안 제작"],
    recommend: ["디자이너·크리에이터", "고품질 이미지가 필요한 마케터", "예술적 표현을 원하는 분"],
    tips: ["'/imagine' 뒤에 영어 프롬프트를 입력하세요", "'--ar 16:9' 등으로 비율을 지정할 수 있어요", "'--style raw'로 사진처럼 현실적인 결과를 얻을 수 있어요"],
    similar: ["flux", "adobe-firefly", "ideogram"],
  },
  {
    id: "flux",
    name: "Flux", emoji: "⚡", cat: "이미지", free: "무료", hot: true,
    desc: "오픈소스 기반 고품질 이미지 생성. 빠르고 무료",
    url: "https://blackforestlabs.ai",
    tagline: "무료로 쓸 수 있는 최고 품질 이미지 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["Flux.1 Schnell 무료 사용", "로컬 설치 가능 (오픈소스)"] },
      { name:"API",   price:"사용량 기반", features:["Flux.1 Pro API", "상업적 이용 가능"] },
    ],
    pros: ["오픈소스로 완전 무료 사용 가능", "Midjourney에 근접하는 품질", "빠른 생성 속도 (Schnell 모델)", "로컬 설치로 프라이버시 보호"],
    cons: ["웹 인터페이스가 친절하지 않음 (서드파티 UI 필요)", "Midjourney만큼의 예술적 감각은 아님"],
    useCases: ["무료로 대량 이미지 생성", "개발자 API 연동 프로젝트", "로컬에서 프라이빗하게 이미지 생성"],
    recommend: ["비용 없이 이미지 AI를 써보고 싶은 분", "개발자·엔지니어", "대량 이미지 생성이 필요한 분"],
    tips: ["Replicate, Fal.ai 같은 서비스에서 웹으로 쉽게 사용할 수 있어요", "ComfyUI로 로컬 설치 시 완전 무료예요"],
    similar: ["midjourney", "adobe-firefly", "dall-e-3"],
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly", emoji: "🔥", cat: "이미지", free: "부분무료", hot: false,
    desc: "어도비 생성형 AI. 상업적 이용 가능한 이미지 생성",
    url: "https://firefly.adobe.com",
    tagline: "저작권 걱정 없이 쓸 수 있는 상업용 이미지 AI",
    plans: [
      { name:"Free",     price:"무료",   features:["월 25크레딧", "Firefly 웹 앱 접근"] },
      { name:"Premium",  price:"$4.99/월", features:["월 100크레딧", "Photoshop·Illustrator 연동"] },
      { name:"Creative Cloud", price:"$54.99/월", features:["어도비 전 앱 포함", "Firefly 무제한"] },
    ],
    pros: ["어도비 라이선스 데이터 학습으로 상업적 이용 안전", "Photoshop·Illustrator에 직접 통합", "텍스트 효과 생성 특화", "저작권 걱정 없음"],
    cons: ["무료 플랜 크레딧이 매우 적음", "순수 예술적 표현은 Midjourney보다 약함"],
    useCases: ["광고·마케팅 상업용 이미지", "Photoshop에서 배경 확장·인페인팅", "브랜드 로고·텍스트 디자인"],
    recommend: ["Adobe CC 구독자", "상업적 이용이 필수인 마케터·디자이너", "저작권에 민감한 기업"],
    tips: ["Photoshop의 'Generative Fill'이 Firefly 기반이에요", "텍스트 효과 생성은 Firefly가 가장 뛰어나요"],
    similar: ["midjourney", "flux", "ideogram"],
  },
  {
    id: "ideogram",
    name: "Ideogram", emoji: "🅰️", cat: "이미지", free: "부분무료", hot: true,
    desc: "텍스트 렌더링 특화 이미지 생성. 타이포그래피·로고 최강",
    url: "https://ideogram.ai",
    tagline: "이미지 안에 글자를 완벽하게 넣는 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["하루 10크레딧", "기본 생성"] },
      { name:"Basic", price:"$7/월",  features:["월 400크레딧", "우선 생성"] },
      { name:"Plus",  price:"$16/월", features:["월 1000크레딧", "고급 편집"] },
    ],
    pros: ["이미지 내 텍스트 렌더링이 타 AI 압도적 1위", "로고·포스터·배너 생성에 최적", "합리적인 가격", "무료 플랜으로 충분히 테스트 가능"],
    cons: ["순수 예술 이미지는 Midjourney보다 약함", "스타일 다양성이 제한적"],
    useCases: ["로고·포스터·배너 디자인", "텍스트가 포함된 SNS 콘텐츠", "명함·패키지 디자인 시안", "메뉴판·안내판 시안"],
    recommend: ["타이포그래피가 중요한 디자이너", "SNS 카드뉴스 제작자", "텍스트 포함 이미지가 자주 필요한 분"],
    tips: ["한글 텍스트도 꽤 잘 렌더링해요", "'Magic prompt' 기능을 켜면 프롬프트를 자동으로 개선해줘요"],
    similar: ["midjourney", "adobe-firefly", "flux"],
  },
  {
    id: "dall-e-3",
    name: "DALL-E 3", emoji: "🖼️", cat: "이미지", free: "유료", hot: false,
    desc: "ChatGPT Plus에 탑재된 이미지 생성 AI",
    url: "https://openai.com/dall-e-3",
    tagline: "ChatGPT에서 바로 쓰는 이미지 생성",
    plans: [
      { name:"ChatGPT Plus", price:"$20/월", features:["DALL-E 3 포함", "ChatGPT와 대화형으로 이미지 생성"] },
      { name:"API",          price:"이미지당 과금", features:["개발자용 API 연동"] },
    ],
    pros: ["ChatGPT와 대화하며 이미지를 수정·발전시킬 수 있음", "별도 앱 없이 ChatGPT 하나로 해결", "프롬프트 이해력 뛰어남"],
    cons: ["ChatGPT Plus 구독 필수", "Midjourney 대비 예술적 퀄리티 아쉬움", "생성 속도 느림"],
    useCases: ["ChatGPT 대화 중 즉석 이미지 생성", "텍스트 설명만으로 정확한 이미지 구현"],
    recommend: ["이미 ChatGPT Plus를 구독 중인 분", "별도 이미지 AI 없이 ChatGPT 하나로 해결하고 싶은 분"],
    tips: ["'이 이미지를 좀 더 밝게 해줘'처럼 대화로 수정할 수 있어요"],
    similar: ["midjourney", "flux", "adobe-firefly"],
  },

  // ── 영상 ──────────────────────────────────────────────────────────────────
  {
    id: "runway",
    name: "Runway", emoji: "🎬", cat: "영상", free: "부분무료", hot: true,
    desc: "텍스트·이미지→영상 생성. 영상 편집 AI 도구 통합 플랫폼",
    url: "https://runwayml.com",
    tagline: "AI 영상 제작의 표준이 된 플랫폼",
    plans: [
      { name:"Free",     price:"무료",   features:["125크레딧 (영상 약 25초분)", "720p 해상도"] },
      { name:"Standard", price:"$15/월", features:["625크레딧/월", "1080p", "무제한 영상 편집기"] },
      { name:"Pro",      price:"$35/월", features:["2250크레딧/월", "4K 내보내기", "워터마크 없음"] },
    ],
    pros: ["Gen-3 Alpha 모델로 업계 최고 수준 영상 품질", "이미지→영상, 텍스트→영상 모두 지원", "배경 제거·모션 트래킹 등 편집 도구 통합", "학습 자료·튜토리얼 풍부"],
    cons: ["크레딧 소모가 빠름", "고품질 영상은 Pro 이상 필요", "긴 영상(1분 이상) 제작은 어려움"],
    useCases: ["유튜브·SNS 숏폼 영상 제작", "광고 영상 시안", "뮤직비디오 제작", "영상 배경 제거 및 합성"],
    recommend: ["유튜브·릴스·틱톡 크리에이터", "영상 편집 비용을 줄이고 싶은 마케터", "영상 프로덕션 스튜디오"],
    tips: ["이미지를 업로드해서 영상으로 만드는 'Image to Video'가 가장 활용도 높아요", "짧고 구체적인 프롬프트가 결과가 더 좋아요"],
    similar: ["sora", "kling", "heygen"],
  },
  {
    id: "sora",
    name: "Sora", emoji: "🎥", cat: "영상", free: "유료", hot: true,
    desc: "OpenAI 텍스트→영상 AI. 물리법칙 반영 고품질 영상 생성",
    url: "https://sora.com",
    tagline: "OpenAI가 만든 가장 현실적인 영상 AI",
    plans: [
      { name:"Plus",       price:"$20/월", features:["최대 720p, 5초 영상 50개/월"] },
      { name:"Pro",        price:"$200/월", features:["1080p, 20초, 500개/월, 우선 생성"] },
    ],
    pros: ["물리 법칙·빛·그림자 표현이 가장 자연스러움", "OpenAI 생태계(ChatGPT)와 연동", "영상 내 카메라 무브먼트 제어 가능"],
    cons: ["가격이 매우 높음 (Pro $200/월)", "생성 시간이 오래 걸림", "짧은 영상(최대 20초)만 지원"],
    useCases: ["광고·브랜드 필름 시안", "영화·드라마 콘셉트 영상", "현실적인 시뮬레이션 영상"],
    recommend: ["최고 품질의 영상이 필요한 전문가", "영화·광고 업계 종사자", "예산이 충분한 크리에이터"],
    tips: ["카메라 무브먼트를 프롬프트에 명시하면(예: 'slow dolly in') 효과가 좋아요"],
    similar: ["runway", "kling", "heygen"],
  },
  {
    id: "kling",
    name: "Kling", emoji: "📹", cat: "영상", free: "부분무료", hot: false,
    desc: "고품질 영상 생성 AI. 한국어 프롬프트 지원",
    url: "https://klingai.com",
    tagline: "가성비 좋은 영상 생성 AI",
    plans: [
      { name:"Free",     price:"무료",   features:["하루 66크레딧", "최대 5초 영상"] },
      { name:"Standard", price:"$10/월", features:["660크레딧/월", "최대 10초 영상", "1080p"] },
    ],
    pros: ["무료 플랜이 넉넉함", "한국어 프롬프트 지원", "가성비 뛰어난 가격 정책", "최대 2분 영상 생성 가능"],
    cons: ["Runway·Sora 대비 영상 품질 아쉬움", "생성 시간이 길 수 있음"],
    useCases: ["무료로 AI 영상 테스트", "SNS 숏폼 영상 대량 생성"],
    recommend: ["비용 부담 없이 영상 AI를 써보고 싶은 분", "한국어로 바로 사용하고 싶은 분"],
    tips: ["한국어로 프롬프트를 입력해도 잘 동작해요"],
    similar: ["runway", "sora", "heygen"],
  },
  {
    id: "heygen",
    name: "HeyGen", emoji: "👤", cat: "영상", free: "부분무료", hot: true,
    desc: "AI 아바타 영상 생성. 마케팅·교육 영상 자동화에 최적",
    url: "https://heygen.com",
    tagline: "내 얼굴 아바타로 영상 자동 제작",
    plans: [
      { name:"Free",  price:"무료",   features:["1분 영상 3개 체험", "워터마크 포함"] },
      { name:"Creator", price:"$29/월", features:["매월 15크레딧", "아바타 생성", "워터마크 없음"] },
      { name:"Business", price:"$89/월", features:["매월 30크레딧", "다국어 립싱크", "브랜드 키트"] },
    ],
    pros: ["내 얼굴 사진으로 AI 아바타 생성", "텍스트 입력만으로 아바타가 말하는 영상 제작", "다국어 자동 더빙·립싱크", "제품 소개·교육 영상에 특화"],
    cons: ["크레딧 소모가 빠름", "아바타 자연스러움이 아직 어색한 경우 있음"],
    useCases: ["유튜브 채널 얼굴 없이 운영", "제품 소개·마케팅 영상", "온라인 강의 영상", "다국어 영상 현지화"],
    recommend: ["카메라 앞에 서기 싫은 크리에이터", "마케팅 영상을 빠르게 대량 제작해야 하는 기업", "온라인 강의 제작자"],
    tips: ["영어 스크립트를 입력하면 한국어 아바타가 말하는 영상을 만들 수 있어요", "본인 얼굴을 촬영해 업로드하면 훨씬 자연스러운 아바타가 만들어져요"],
    similar: ["runway", "sora", "kling"],
  },

  // ── 코딩 ──────────────────────────────────────────────────────────────────
  {
    id: "cursor",
    name: "Cursor", emoji: "💻", cat: "코딩", free: "부분무료", hot: true,
    desc: "AI 코드 에디터. Claude·GPT 탑재로 코딩 생산성 혁신",
    url: "https://cursor.sh",
    tagline: "코딩 생산성을 10배 높여주는 AI 에디터",
    plans: [
      { name:"Free",    price:"무료",   features:["하루 50회 자동완성", "Claude/GPT 제한 사용"] },
      { name:"Pro",     price:"$20/월", features:["무제한 자동완성", "Claude Sonnet·GPT-4o 사용", "더 빠른 응답"] },
      { name:"Business",price:"$40/월", features:["팀 관리 기능", "Privacy Mode"] },
    ],
    pros: ["VS Code 기반으로 기존 익스텐션·설정 그대로 사용", "코드베이스 전체를 이해하고 수정 제안", "자연어로 코드 작성·수정 지시 가능", "탭 자동완성의 품질이 압도적"],
    cons: ["Pro 구독 시 비용 발생", "AI 제안이 항상 완벽하지 않아 검토 필요"],
    useCases: ["웹·앱 개발 전반", "레거시 코드 리팩토링", "버그 수정 및 디버깅", "테스트 코드 자동 생성"],
    recommend: ["웹·앱 개발자 전반", "코딩 생산성을 극대화하고 싶은 개발자", "AI로 코딩을 배우는 입문자"],
    tips: ["Ctrl+K로 코드 블록을 선택해 '이 함수를 최적화해줘'처럼 지시하세요", "Composer(Ctrl+I)로 여러 파일을 한번에 수정할 수 있어요", "@파일명으로 특정 파일을 참조해서 질문할 수 있어요"],
    similar: ["claude-code", "github-copilot", "v0"],
  },
  {
    id: "claude-code",
    name: "Claude Code", emoji: "⌨️", cat: "코딩", free: "유료", hot: true,
    desc: "터미널 AI 코딩 도우미. 파일 읽기·수정·실행 자동화",
    url: "https://claude.ai/code",
    tagline: "터미널에서 AI와 함께 전체 프로젝트를 코딩",
    plans: [
      { name:"Claude Pro/Max", price:"$20~100/월", features:["Claude API 사용량 기반 과금"] },
    ],
    pros: ["프로젝트 전체 파일 구조를 읽고 수정", "터미널 명령어 직접 실행 가능", "깃 커밋·PR 생성까지 자동화", "에디터 없이 자연어로 개발 가능"],
    cons: ["Claude 구독 필요", "터미널에 익숙하지 않으면 진입장벽 있음"],
    useCases: ["프로젝트 전체 리팩토링", "자동화 스크립트 작성·실행", "복잡한 버그 수정", "새 기능 전체 구현"],
    recommend: ["개발 자동화를 원하는 개발자", "터미널을 편하게 쓰는 개발자", "Claude를 이미 구독 중인 개발자"],
    tips: ["'/add' 명령으로 분석할 파일·폴더를 추가하세요", "CLAUDE.md 파일에 프로젝트 규칙을 적어두면 매번 설명 안 해도 돼요"],
    similar: ["cursor", "github-copilot", "v0"],
  },
  {
    id: "v0",
    name: "v0", emoji: "🔲", cat: "코딩", free: "부분무료", hot: true,
    desc: "Vercel의 UI 생성 AI. 텍스트 한 줄로 React 컴포넌트 즉시 생성",
    url: "https://v0.dev",
    tagline: "말로 설명하면 UI 코드가 뚝딱 나오는 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["월 200크레딧", "기본 UI 생성"] },
      { name:"Premium", price:"$20/월", features:["월 5000크레딧", "더 복잡한 UI 생성"] },
    ],
    pros: ["'로그인 폼 만들어줘'만으로 완성된 React+Tailwind 코드 생성", "브라우저에서 바로 미리보기·수정 가능", "Shadcn UI 기반 현대적 디자인", "Vercel에 원클릭 배포"],
    cons: ["React/Next.js 외 프레임워크는 약함", "복잡한 비즈니스 로직 구현은 아직 한계"],
    useCases: ["랜딩 페이지 빠른 프로토타이핑", "대시보드·폼 UI 빠른 생성", "React 컴포넌트 시안 제작"],
    recommend: ["프론트엔드 개발자", "디자인→코드 변환이 필요한 기획자·디자이너", "빠른 MVP 제작이 필요한 스타트업"],
    tips: ["스크린샷을 붙여넣으면 해당 디자인과 비슷한 코드를 만들어줘요", "생성된 코드를 Cursor에 붙여넣어 계속 발전시킬 수 있어요"],
    similar: ["cursor", "claude-code", "github-copilot"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot", emoji: "🐙", cat: "코딩", free: "유료", hot: false,
    desc: "GitHub AI 코딩 도우미. VS Code·JetBrains 완벽 연동",
    url: "https://github.com/features/copilot",
    tagline: "GitHub이 만든 개발자 표준 AI 도우미",
    plans: [
      { name:"Individual", price:"$10/월", features:["코드 자동완성", "채팅 기반 질문·수정"] },
      { name:"Business",   price:"$19/월", features:["팀 관리", "기업 보안 정책"] },
    ],
    pros: ["GitHub 코드베이스 학습으로 정확한 자동완성", "VS Code·JetBrains·Neovim 등 대부분 IDE 지원", "안정적이고 검증된 서비스"],
    cons: ["Cursor에 비해 프로젝트 전체 이해력 약함", "비슷한 가격에 Cursor가 더 강력함"],
    useCases: ["IDE 자동완성 보조", "함수 설명 자동 생성", "단위 테스트 자동 작성"],
    recommend: ["JetBrains(IntelliJ, PyCharm 등) 사용자", "GitHub Enterprise 환경의 팀"],
    tips: ["주석으로 원하는 기능을 설명하면 코드를 자동 완성해줘요"],
    similar: ["cursor", "claude-code", "v0"],
  },

  // ── 생산성 ────────────────────────────────────────────────────────────────
  {
    id: "gamma",
    name: "Gamma", emoji: "📊", cat: "생산성", free: "부분무료", hot: true,
    desc: "AI로 프레젠테이션·문서 자동 생성. PPT 대체 솔루션",
    url: "https://gamma.app",
    tagline: "AI가 PPT를 대신 만들어주는 서비스",
    plans: [
      { name:"Free",  price:"무료",   features:["400AI 크레딧", "무제한 뷰어", "Gamma 워터마크"] },
      { name:"Plus",  price:"$10/월", features:["무제한 AI 생성", "워터마크 없음", "분석 기능"] },
      { name:"Pro",   price:"$20/월", features:["우선 처리", "커스텀 폰트·도메인"] },
    ],
    pros: ["주제만 입력하면 완성된 슬라이드 자동 생성", "디자인이 기본 이상으로 예쁨", "웹 기반으로 공유·협업 쉬움", "PDF·PPT로 내보내기 가능"],
    cons: ["세밀한 레이아웃 조정은 PowerPoint만 못함", "복잡한 차트·표 삽입은 번거로움"],
    useCases: ["빠른 발표 자료 제작", "보고서·제안서 자동화", "팀 공유용 문서 제작"],
    recommend: ["발표 자료 만들기 귀찮은 모든 분", "PPT 디자인에 자신 없는 분", "빠른 제안서가 필요한 영업·기획자"],
    tips: ["주제를 구체적으로 입력할수록 퀄리티가 높아져요", "생성 후 AI Chat으로 슬라이드를 추가·수정할 수 있어요"],
    similar: ["notion-ai", "napkin", "chatgpt"],
  },
  {
    id: "notion-ai",
    name: "Notion AI", emoji: "📝", cat: "생산성", free: "부분무료", hot: false,
    desc: "Notion 탑재 AI. 문서 요약·초안 작성·번역 자동화",
    url: "https://notion.so",
    tagline: "Notion 안에서 AI로 문서 작업 자동화",
    plans: [
      { name:"Free + AI",  price:"$10/월", features:["Notion Free + AI 무제한"] },
      { name:"Plus + AI",  price:"$18/월", features:["Notion Plus + AI 무제한"] },
    ],
    pros: ["Notion 워크스페이스 안에서 바로 사용", "기존 문서를 AI로 즉시 요약·번역", "회의록 자동 정리"],
    cons: ["Notion 구독 추가 비용 발생", "독립 AI 서비스보다 기능 제한적"],
    useCases: ["회의록·업무 일지 자동 요약", "기존 Notion 문서 번역", "마케팅 카피 초안 작성"],
    recommend: ["Notion을 이미 쓰고 있는 분", "팀 문서 자동화가 필요한 분"],
    tips: ["'/' 명령어 → AI 블록으로 바로 사용할 수 있어요"],
    similar: ["gamma", "napkin", "chatgpt"],
  },
  {
    id: "napkin",
    name: "Napkin", emoji: "🗂️", cat: "생산성", free: "부분무료", hot: true,
    desc: "텍스트를 다이어그램·인포그래픽으로 자동 변환",
    url: "https://napkin.ai",
    tagline: "글을 붙여넣으면 다이어그램이 자동으로",
    plans: [
      { name:"Free",  price:"무료",   features:["기본 다이어그램 생성"] },
      { name:"Pro",   price:"$16/월", features:["무제한 생성", "고해상도 내보내기", "커스텀 스타일"] },
    ],
    pros: ["텍스트 붙여넣기만으로 자동 다이어그램 생성", "인포그래픽·플로우차트·마인드맵 모두 지원", "보고서·발표 자료 비주얼화에 최적"],
    cons: ["복잡한 기술 다이어그램은 Mermaid/draw.io가 더 정확함"],
    useCases: ["보고서·제안서 인포그래픽 제작", "프로세스 플로우차트 빠른 생성", "아이디어 마인드맵 시각화"],
    recommend: ["보고서·제안서를 자주 쓰는 기획자", "시각화에 약한 분"],
    tips: ["요약된 텍스트를 입력할수록 더 깔끔한 결과가 나와요"],
    similar: ["gamma", "notion-ai", "chatgpt"],
  },

  // ── 음성 ──────────────────────────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs", emoji: "🔊", cat: "음성", free: "부분무료", hot: true,
    desc: "텍스트→음성 AI. 자연스러운 TTS, 100개 이상 언어 지원",
    url: "https://elevenlabs.io",
    tagline: "가장 자연스러운 AI 목소리 생성 서비스",
    plans: [
      { name:"Free",    price:"무료",   features:["월 10,000자 TTS", "3개 커스텀 음성"] },
      { name:"Starter", price:"$5/월",  features:["월 30,000자", "30개 커스텀 음성"] },
      { name:"Creator", price:"$22/월", features:["월 100,000자", "무제한 커스텀 음성"] },
    ],
    pros: ["현존 가장 자연스러운 TTS 품질", "내 목소리 복제 기능", "100개 이상 언어 지원", "감정·속도·억양 조절 가능"],
    cons: ["많이 쓸수록 비용 증가", "한국어 자연스러움은 아직 개선 여지 있음"],
    useCases: ["유튜브·팟캐스트 나레이션", "광고·영상 더빙", "오디오북 제작", "다국어 영상 자동 더빙"],
    recommend: ["유튜브·팟캐스트 크리에이터", "영상 제작자", "언어 장벽 없는 콘텐츠가 필요한 분"],
    tips: ["'Voice Cloning'으로 내 목소리를 학습시켜 자동 나레이션을 만들 수 있어요", "HeyGen과 조합하면 AI 아바타+내 목소리 영상을 만들 수 있어요"],
    similar: ["suno", "clova-note", "chatgpt"],
  },
  {
    id: "suno",
    name: "Suno", emoji: "🎵", cat: "음성", free: "부분무료", hot: true,
    desc: "텍스트로 음악 생성. 가사·멜로디·편곡 자동 작곡",
    url: "https://suno.ai",
    tagline: "음악을 몰라도 나만의 노래를 만드는 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["하루 50크레딧 (약 10곡)", "비상업적 이용"] },
      { name:"Pro",   price:"$10/월", features:["2500크레딧/월 (약 500곡)", "상업적 이용"] },
      { name:"Premier", price:"$30/월", features:["10000크레딧/월", "우선 생성"] },
    ],
    pros: ["장르·분위기·가사를 텍스트로 입력하면 완성된 노래 생성", "보컬·악기 편성 품질이 놀라울 수준", "무료 플랜이 넉넉함"],
    cons: ["생성된 음악 저작권이 복잡함 (유료 플랜 상업적 이용 가능)", "세밀한 악기 편곡 제어 불가"],
    useCases: ["유튜브·SNS 배경음악", "광고 징글 제작", "개인 앨범 제작", "영상 OST"],
    recommend: ["배경음악이 필요한 크리에이터", "음악을 배우지 않았지만 작곡에 관심 있는 분", "광고 음악 제작 비용을 줄이고 싶은 마케터"],
    tips: ["장르(K-pop, lo-fi, jazz)와 분위기(upbeat, melancholic)를 구체적으로 쓸수록 원하는 결과가 나와요", "'Custom mode'에서 가사를 직접 입력할 수 있어요"],
    similar: ["elevenlabs", "clova-note"],
  },
  {
    id: "clova-note",
    name: "Clova Note", emoji: "🗒️", cat: "음성", free: "부분무료", hot: false,
    desc: "네이버 AI 회의록. 한국어 최강 음성 인식 + 자동 요약",
    url: "https://clovanote.naver.com",
    tagline: "회의 녹음만 하면 요약까지 자동으로",
    plans: [
      { name:"Free",     price:"무료",   features:["월 300분 녹음", "AI 요약 제한"] },
      { name:"Premium",  price:"₩5,500/월", features:["월 3,000분", "AI 요약 무제한"] },
    ],
    pros: ["한국어 음성 인식 정확도 국내 최고 수준", "화자 분리 기능 (누가 말했는지 구분)", "회의 내용 자동 요약", "네이버 생태계 연동"],
    cons: ["한국어 특화로 외국어 성능은 보통", "오프라인 사용 불가"],
    useCases: ["회의·강의·인터뷰 자동 기록", "회의록 자동 작성", "음성 메모 텍스트 변환"],
    recommend: ["회의록 작성이 번거로운 직장인", "강의를 녹음해 정리하는 학생", "인터뷰·취재가 많은 기자"],
    tips: ["회의 전 앱을 열어두면 자동으로 녹음·전사가 시작돼요", "AI 요약 기능으로 핵심 내용만 빠르게 확인할 수 있어요"],
    similar: ["elevenlabs", "suno", "chatgpt"],
  },

  // ── 번역 ──────────────────────────────────────────────────────────────────
  {
    id: "deepl",
    name: "DeepL", emoji: "🌐", cat: "번역", free: "부분무료", hot: false,
    desc: "AI 번역 끝판왕. 자연스러운 문맥 번역, 문서 파일 번역 지원",
    url: "https://deepl.com",
    tagline: "가장 자연스러운 번역 퀄리티를 제공하는 AI",
    plans: [
      { name:"Free",  price:"무료",   features:["월 500,000자 번역", "파일 번역 3개/월"] },
      { name:"Pro",   price:"$8.74/월", features:["무제한 번역", "무제한 파일 번역", "API 접근"] },
    ],
    pros: ["구글 번역 대비 훨씬 자연스러운 문맥 번역", "PDF·Word·PowerPoint 파일 통째로 번역", "용어집 기능으로 전문 용어 통일", "데이터 보안 정책 우수"],
    cons: ["지원 언어가 구글 번역보다 적음 (31개)", "무료 플랜 문서 번역 횟수 제한"],
    useCases: ["영어 논문·계약서 번역", "비즈니스 이메일 번역", "외국어 기사·뉴스 번역"],
    recommend: ["영어 문서를 자주 번역하는 직장인", "정확한 번역이 중요한 연구자·번역가", "기업 계약서·문서 번역"],
    tips: ["번역 후 하단의 '대안 번역'을 확인하면 더 자연스러운 표현을 고를 수 있어요", "파일 번역은 원본 서식을 그대로 유지해줘요"],
    similar: ["papago", "chatgpt", "gemini"],
  },
  {
    id: "papago",
    name: "Papago", emoji: "📖", cat: "번역", free: "무료", hot: false,
    desc: "네이버 번역. 한국어 특화, 일상·여행 번역에 최적화",
    url: "https://papago.naver.com",
    tagline: "한국인을 위한 가장 친숙한 번역기",
    plans: [
      { name:"Free",  price:"완전 무료", features:["번역 무제한", "이미지·음성 번역", "실시간 회화 번역"] },
    ],
    pros: ["완전 무료", "한국어 번역 품질 우수", "이미지 속 텍스트 번역", "음성 실시간 번역·회화", "오프라인 모드 지원"],
    cons: ["DeepL 대비 긴 문서 번역은 부족함", "전문 비즈니스 문서는 DeepL이 더 자연스러움"],
    useCases: ["일본·중국어 여행 시 간판·메뉴 번역", "외국 친구와 실시간 채팅 번역", "일상적인 짧은 문장 번역"],
    recommend: ["해외 여행 준비 중인 분", "일상적인 번역이 필요한 분", "무료로 편하게 쓰고 싶은 분"],
    tips: ["카메라 번역으로 간판·메뉴판을 실시간으로 번역할 수 있어요", "음성 회화 기능으로 외국인과 실시간 대화가 가능해요"],
    similar: ["deepl", "chatgpt", "gemini"],
  },
];

// 카테고리 색상 맵 (전체 파일 공유)
const CAT_ICON_BG = {
  "챗봇":  "bg-indigo-50 dark:bg-indigo-500/10",
  "이미지":"bg-rose-50 dark:bg-rose-500/10",
  "영상":  "bg-violet-50 dark:bg-violet-500/10",
  "코딩":  "bg-emerald-50 dark:bg-emerald-500/10",
  "생산성":"bg-amber-50 dark:bg-amber-500/10",
  "음성":  "bg-sky-50 dark:bg-sky-500/10",
  "번역":  "bg-teal-50 dark:bg-teal-500/10",
};
const CAT_TEXT = {
  "챗봇":  "text-indigo-500",
  "이미지":"text-rose-500",
  "영상":  "text-violet-500",
  "코딩":  "text-emerald-500",
  "생산성":"text-amber-500",
  "음성":  "text-sky-500",
  "번역":  "text-teal-500",
};
const FREE_CLASS = {
  "무료":    "bg-emerald-100 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-400",
  "부분무료":"bg-amber-100 dark:bg-amber-500/15 text-amber-700 dark:text-amber-400",
  "유료":    "bg-rose-100 dark:bg-rose-500/15 text-rose-700 dark:text-rose-400",
};
